export const ErrorCategory = [
  "SOURCE_ACCESS_ERROR",
  "SOURCE_PARSE_ERROR",
  "AI_EXTRACTION_ERROR",
  "DOMAIN_NORMALIZATION_ERROR",
  "DOMAIN_VALIDATION_ERROR",
  "ADMIN_CONTRACT_DRIFT",
  "ADMIN_AUTH_ERROR",
  "ADMIN_CONTEXT_ERROR",
  "ADMIN_NAVIGATION_ERROR",
  "ADMIN_WRITE_ERROR",
  "ADMIN_SAVE_ERROR",
  "READBACK_MISMATCH",
  "DUPLICATE_DETECTED",
  "UNKNOWN_ERROR",
] as const;

export type ErrorCategory = (typeof ErrorCategory)[number];

export const ValidationCode = [
  "MISSING_CATEGORY",
  "MISSING_PRODUCT_NAME",
  "MISSING_MENU_NUMBER",
  "DUPLICATE_SOURCE_MENU_NUMBER",
  "DUPLICATE_ASSIGNED_MENU_NUMBER",
  "DUPLICATE_PRODUCT",
  "MISSING_BASE_PRICE",
  "MALFORMED_PRICE",
  "MISSING_VARIANT",
  "INVALID_BASE_VARIANT",
  "AMBIGUOUS_BASE_VARIANT",
  "INVALID_VARIANT_SURCHARGE",
  "UNEXPECTED_NEGATIVE_SURCHARGE",
  "SOURCE_PRICE_CONFLICT",
  "MISSING_SOURCE_SUPPORTED_INGREDIENTS",
  "AMBIGUOUS_INGREDIENT_EXTRACTION",
  "MALFORMED_PRODUCT_CHOICE",
  "AMBIGUOUS_MENU_STRUCTURE",
  "UNSUPPORTED_STRUCTURE",
  "MISSING_SOURCE_ID",
  "DUPLICATE_SOURCE_ID",
] as const;

export type ValidationCode = (typeof ValidationCode)[number];
