export {
  freezeWritePlan,
  assertWritePlanImmutable,
  createMigrationWritePlan,
  planCreateProduct,
  planSkipProduct,
  planBlockProduct,
  planReviewProduct,
  planUpdateProduct,
  type WritePlanAction,
  type WritePlanEntityType,
  type ProductIdentityKey,
  type PlannedProductPayload,
  type WritePlanOperation,
  type MigrationWritePlan,
} from "./writePlan.js";
export {
  canTransitionOp,
  compareProductExact,
  resolveCreateResume,
  executeMigrationPlan,
  matchDestinationByEvidence,
  resolveDestinationIdentity,
  type DestinationPort,
  type DestinationProduct,
  type DestinationMatchResult,
  type ExecutorGate,
  type ExecuteResult,
} from "./executor.js";
